name: Testing

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  setup-build:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Setup Conda
      uses: s-weigand/setup-conda@v1.2.1
      with:
        update-conda: false
        python-version: ${{ matrix.python-version }}

    - name: Install Env
      shell: bash
      run: |
        python --version
        conda create -n mth5-test python=${{ matrix.python-version }}
        source activate mth5-test
        conda install pytest=7.1.2
        conda install pytest-cov
        conda install pytest-subtests
        pip install git+https://github.com/kujaku11/mt_metadata.git

    - name: Install Our Package
      shell: bash
      run: |
        source activate mth5-test
        pip install -e .
        conda list
        
    - name: Install Jupyter and dependencies
      run: |
        source activate mth5-test
        pip install jupyter
        pip install ipykernel
        pip install ipympl
        python -m ipykernel install --user --name mth5-test
        # Install any other dependencies you need

    - name: Execute Jupyter Notebooks
      run: |
        source activate mth5-test
        jupyter nbconvert --to notebook --execute docs/examples/notebooks/make_mth5_driver_v0.2.0.ipynb

    - name: Run Tests
      shell: bash
      run: |
        source activate mth5-test
        pytest -rA --cov=./ --cov-report=xml --cov=mth5

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        flags: tests
        fail_ci_if_error: true
        verbose: true
      
