name: Testing

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  setup-build:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Setup Conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: false
        python-version: ${{ matrix.python-version }}

    - name: Install Env
      shell: bash
      run: |
        python --version
        conda create -n mth5-test python=${{ matrix.python-version }}
        source activate mth5-test
        conda install pytest=7.1.2
        conda install pytest-cov
        conda install pytest-subtests
        pip install git+https://github.com/kujaku11/mt_metadata.git@fcs
        
    - name: Install Our Package
      shell: bash
      run: |
        source activate mth5-test
        pip install -e .
        conda list

    - name: Run Tests
      shell: bash
      run: |
        source activate mth5-test
        pytest -rA --cov=./ --cov-report=xml --cov=mth5
        
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v3
      with:
        flags: tests
        fail_ci_if_error: true
        verbose: true
